import datetime
from bson import ObjectId
from pydantic import BaseModel, Field
from typing import Optional, List

from pydantic import GetPydanticSchema
from pydantic_core import CoreSchema, PydanticCustomError, core_schema


class PyObjectId(ObjectId):
    """Custom type to handle MongoDB ObjectIds in Pydantic models (V2)."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: GetPydanticSchema
    ) -> CoreSchema:
        """Defines the Pydantic V2 Core Schema for validation and serialization."""

        def validate_object_id(value):
            if isinstance(value, ObjectId):
                return value
            if isinstance(value, str) and ObjectId.is_valid(value):
                return ObjectId(value)
            raise PydanticCustomError("object_id_invalid", "Invalid ObjectId format.")

        return core_schema.json_or_python_schema(
            python_schema=core_schema.chain_schema(
                [
                    core_schema.any_schema(),
                    core_schema.no_info_plain_validator_function(validate_object_id),
                ]
            ),
            json_schema=core_schema.str_schema(),
            serialization=core_schema.to_string_ser_schema(),
        )


class Task(BaseModel):
    """The structure of a single task (reusing definition from schemas.py for consistency)."""

    task_id: str = Field(
        description="A unique short ID for this task (e.g., 'T01', 'T02')."
    )
    description: str = Field(description="A clear, actionable description of the task.")
    estimated_duration_days: int = Field(description="Estimated time in full days.")
    dependencies: List[str] = Field(
        description="A list of task_ids that must be completed first."
    )
    priority: str = Field(description="The priority level: 'High', 'Medium', or 'Low'.")
    suggested_deadline: str = Field(
        description="The suggested completion date in YYYY-MM-DD format."
    )


class PlanDB(BaseModel):
    """The complete structured plan model for storage in MongoDB."""

    id: PyObjectId = Field(default_factory=PyObjectId, alias="_id")
    user_id: Optional[str] = Field(
        None, description="ID of the user who created the plan."
    )
    goal_text: str = Field(description="The original goal submitted by the user.")
    context: Optional[str] = Field(
        None, description="Additional context provided for the LLM."
    )
    summary: str = Field(description="High-level summary generated by the LLM.")
    tasks: List[Task] = Field(description="The detailed list of generated tasks.")
    created_at: datetime.datetime = Field(default_factory=datetime.datetime.utcnow)

    model_config = {
        "populate_by_name": True,
        "json_encoders": {ObjectId: str},
        "arbitrary_types_allowed": True,
    }
